/**
 * km-monitor/src/km-writer.ts
 *
 * Knowledge Map Writer — persists verified "gold" entries to the OpenClaw
 * memory index (file-backed KM) and to a human-readable Markdown log for
 * full auditability.
 *
 * Three persistence strategies are used in parallel:
 *   1. **Markdown log** (`~/.openclaw/km-monitor/knowledge-map.md`) — append-only,
 *      human-readable, includes full provenance metadata.
 *   2. **JSON index** (`~/.openclaw/km-monitor/knowledge-map.json`) — machine-readable
 *      array of all GoldEntry objects, used for programmatic search.
 *   3. **Audit log** (`~/.openclaw/km-monitor/audit.ndjson`) — append-only NDJSON
 *      log of every KmAuditEvent, providing full change-log traceability.
 *
 * Enhanced in v1.1.0:
 *   - Added audit log (NDJSON) for full change-log traceability.
 *   - Markdown entries now include extractionModel and rawConfidence fields.
 *   - Added `searchKnowledgeMapBySource()` for source-filtered retrieval.
 *   - Added `getKnowledgeMapStats()` for observability.
 */

import {
  existsSync,
  mkdirSync,
  appendFileSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import type { GoldEntry, KmAuditEvent } from "./types.js";

// ---------------------------------------------------------------------------
// Path helpers
// ---------------------------------------------------------------------------

function resolveKmDir(): string {
  const home = process.env.HOME ?? "/tmp";
  return (
    process.env.KM_MONITOR_KM_DIR ??
    join(home, ".openclaw", "km-monitor")
  );
}

function ensureDir(dir: string): void {
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
}

// ---------------------------------------------------------------------------
// Markdown log
// ---------------------------------------------------------------------------

function formatMarkdownEntry(entry: GoldEntry): string {
  const tags = entry.tags.map((t) => `\`${t}\``).join(", ");
  const confidence = (entry.confidence * 100).toFixed(0);
  const rawConf =
    entry.provenance.rawConfidence !== undefined
      ? ` _(raw: ${(entry.provenance.rawConfidence * 100).toFixed(1)}%)_`
      : "";
  const modelStr = entry.provenance.extractionModel
    ? `\`${entry.provenance.extractionModel}\``
    : "_default_";

  return [
    `## ${entry.title}`,
    ``,
    entry.body,
    ``,
    `| Field | Value |`,
    `|-------|-------|`,
    `| **ID** | \`${entry.id}\` |`,
    `| **Confidence** | ${confidence}%${rawConf} |`,
    `| **Tags** | ${tags} |`,
    `| **Added** | ${entry.addedAt} |`,
    `| **Source** | \`${entry.provenance.source}\` |`,
    `| **Conversation ID** | \`${entry.provenance.conversationId}\` |`,
    `| **Origin URL** | ${entry.provenance.originUrl ? `[${entry.provenance.originUrl}](${entry.provenance.originUrl})` : "_none_"} |`,
    `| **Extracted by** | \`${entry.provenance.extractedBy}\` |`,
    `| **Extraction model** | ${modelStr} |`,
    `| **Extracted at** | ${entry.provenance.extractedAt} |`,
    ``,
    `---`,
    ``,
  ].join("\n");
}

/** Append gold entries to the Markdown knowledge-map log. */
function appendToMarkdownLog(entries: GoldEntry[]): void {
  const dir = resolveKmDir();
  ensureDir(dir);
  const path = join(dir, "knowledge-map.md");

  // Write header if file is new.
  if (!existsSync(path)) {
    writeFileSync(
      path,
      [
        `# Knowledge Map`,
        ``,
        `_Auto-generated by km-monitor v1.1.0. Do not edit manually._`,
        `_Every entry is traceable to its source conversation via the provenance table._`,
        ``,
      ].join("\n"),
      "utf-8",
    );
  }

  for (const entry of entries) {
    appendFileSync(path, formatMarkdownEntry(entry), "utf-8");
  }
}

// ---------------------------------------------------------------------------
// JSON index
// ---------------------------------------------------------------------------

/** Load the existing JSON index, or return an empty array. */
function loadJsonIndex(): GoldEntry[] {
  const path = join(resolveKmDir(), "knowledge-map.json");
  if (!existsSync(path)) return [];
  try {
    return JSON.parse(readFileSync(path, "utf-8")) as GoldEntry[];
  } catch {
    return [];
  }
}

/** Persist the JSON index to disk. */
function saveJsonIndex(entries: GoldEntry[]): void {
  const dir = resolveKmDir();
  ensureDir(dir);
  const path = join(dir, "knowledge-map.json");
  writeFileSync(path, JSON.stringify(entries, null, 2), "utf-8");
}

// ---------------------------------------------------------------------------
// Audit log
// ---------------------------------------------------------------------------

/** Append an audit event to the NDJSON audit log. */
function appendAuditEvent(event: KmAuditEvent): void {
  const dir = resolveKmDir();
  ensureDir(dir);
  const path = join(dir, "audit.ndjson");
  appendFileSync(path, JSON.stringify(event) + "\n", "utf-8");
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface KmWriteResult {
  /** Number of entries successfully written. */
  written: number;
  /** Number of entries skipped because they were already in the index. */
  duplicatesSkipped: number;
  /** Absolute path to the Markdown log. */
  markdownLogPath: string;
  /** Absolute path to the JSON index. */
  jsonIndexPath: string;
  /** Absolute path to the audit log. */
  auditLogPath: string;
}

/**
 * Write a batch of gold entries to the Knowledge Map.
 * Deduplicates by entry ID before writing.
 * Appends audit events for every add and skip-duplicate action.
 */
export function writeToKnowledgeMap(entries: GoldEntry[]): KmWriteResult {
  const dir = resolveKmDir();
  const existing = loadJsonIndex();
  const existingIds = new Set(existing.map((e) => e.id));
  const now = new Date().toISOString();

  const newEntries = entries.filter((e) => !existingIds.has(e.id));
  const duplicates = entries.filter((e) => existingIds.has(e.id));
  const duplicatesSkipped = duplicates.length;

  // Audit: log skipped duplicates.
  for (const dup of duplicates) {
    appendAuditEvent({
      kind: "km-audit",
      timestamp: now,
      action: "skip-duplicate",
      entryId: dup.id,
      entryTitle: dup.title,
      source: dup.provenance.source,
      conversationId: dup.provenance.conversationId,
    });
  }

  if (newEntries.length > 0) {
    appendToMarkdownLog(newEntries);
    saveJsonIndex([...existing, ...newEntries]);

    // Audit: log each new addition.
    for (const entry of newEntries) {
      appendAuditEvent({
        kind: "km-audit",
        timestamp: now,
        action: "add",
        entryId: entry.id,
        entryTitle: entry.title,
        source: entry.provenance.source,
        conversationId: entry.provenance.conversationId,
      });
    }
  }

  return {
    written: newEntries.length,
    duplicatesSkipped,
    markdownLogPath: join(dir, "knowledge-map.md"),
    jsonIndexPath: join(dir, "knowledge-map.json"),
    auditLogPath: join(dir, "audit.ndjson"),
  };
}

/**
 * Search the JSON index for entries matching a query string.
 * Simple case-insensitive substring match across title, body, and tags.
 */
export function searchKnowledgeMap(query: string): GoldEntry[] {
  const lower = query.toLowerCase();
  return loadJsonIndex().filter(
    (e) =>
      e.title.toLowerCase().includes(lower) ||
      e.body.toLowerCase().includes(lower) ||
      e.tags.some((t) => t.toLowerCase().includes(lower)),
  );
}

/**
 * Search the JSON index filtered to a specific LLM source.
 * Useful for auditing what a particular interface has contributed to the KM.
 */
export function searchKnowledgeMapBySource(source: string): GoldEntry[] {
  return loadJsonIndex().filter(
    (e) => e.provenance.source === source,
  );
}

/** Return all entries in the JSON index. */
export function getAllKnowledgeMapEntries(): GoldEntry[] {
  return loadJsonIndex();
}

/** Return aggregate statistics about the Knowledge Map. */
export function getKnowledgeMapStats(): {
  totalEntries: number;
  bySource: Record<string, number>;
  avgConfidence: number;
  topTags: Array<{ tag: string; count: number }>;
} {
  const entries = loadJsonIndex();
  const bySource: Record<string, number> = {};
  const tagCounts: Record<string, number> = {};
  let totalConfidence = 0;

  for (const entry of entries) {
    const src = entry.provenance.source;
    bySource[src] = (bySource[src] ?? 0) + 1;
    totalConfidence += entry.confidence;
    for (const tag of entry.tags) {
      tagCounts[tag] = (tagCounts[tag] ?? 0) + 1;
    }
  }

  const topTags = Object.entries(tagCounts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 10)
    .map(([tag, count]) => ({ tag, count }));

  return {
    totalEntries: entries.length,
    bySource,
    avgConfidence:
      entries.length > 0 ? totalConfidence / entries.length : 0,
    topTags,
  };
}
