/**
 * km-monitor/src/km-writer.ts
 *
 * Knowledge Map Writer — persists verified "gold" entries to the OpenClaw
 * memory index (file-backed KM) and to a human-readable Markdown log for
 * full auditability.
 *
 * Two persistence strategies are used in parallel:
 *   1. **Markdown log** (`~/.openclaw/km-monitor/knowledge-map.md`) — append-only,
 *      human-readable, includes full provenance metadata.
 *   2. **JSON index** (`~/.openclaw/km-monitor/knowledge-map.json`) — machine-readable
 *      array of all GoldEntry objects, used for programmatic search.
 */

import {
  existsSync,
  mkdirSync,
  appendFileSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { join, dirname } from "node:path";
import type { GoldEntry } from "./types.js";

// ---------------------------------------------------------------------------
// Path helpers
// ---------------------------------------------------------------------------

function resolveKmDir(): string {
  const home = process.env.HOME ?? "/tmp";
  return (
    process.env.KM_MONITOR_KM_DIR ??
    join(home, ".openclaw", "km-monitor")
  );
}

function ensureDir(dir: string): void {
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
}

// ---------------------------------------------------------------------------
// Markdown log
// ---------------------------------------------------------------------------

function formatMarkdownEntry(entry: GoldEntry): string {
  const tags = entry.tags.map((t) => `\`${t}\``).join(", ");
  const confidence = (entry.confidence * 100).toFixed(0);
  return [
    `## ${entry.title}`,
    ``,
    entry.body,
    ``,
    `| Field | Value |`,
    `|-------|-------|`,
    `| **ID** | \`${entry.id}\` |`,
    `| **Confidence** | ${confidence}% |`,
    `| **Tags** | ${tags} |`,
    `| **Added** | ${entry.addedAt} |`,
    `| **Source** | \`${entry.provenance.source}\` |`,
    `| **Conversation ID** | \`${entry.provenance.conversationId}\` |`,
    `| **Origin URL** | ${entry.provenance.originUrl ?? "_none_"} |`,
    `| **Extracted by** | \`${entry.provenance.extractedBy}\` |`,
    `| **Extracted at** | ${entry.provenance.extractedAt} |`,
    ``,
    `---`,
    ``,
  ].join("\n");
}

/** Append gold entries to the Markdown knowledge-map log. */
function appendToMarkdownLog(entries: GoldEntry[]): void {
  const dir = resolveKmDir();
  ensureDir(dir);
  const path = join(dir, "knowledge-map.md");

  // Write header if file is new.
  if (!existsSync(path)) {
    writeFileSync(
      path,
      `# Knowledge Map\n\n_Auto-generated by km-monitor. Do not edit manually._\n\n`,
      "utf-8",
    );
  }

  for (const entry of entries) {
    appendFileSync(path, formatMarkdownEntry(entry), "utf-8");
  }
}

// ---------------------------------------------------------------------------
// JSON index
// ---------------------------------------------------------------------------

/** Load the existing JSON index, or return an empty array. */
function loadJsonIndex(): GoldEntry[] {
  const path = join(resolveKmDir(), "knowledge-map.json");
  if (!existsSync(path)) return [];
  try {
    return JSON.parse(readFileSync(path, "utf-8")) as GoldEntry[];
  } catch {
    return [];
  }
}

/** Persist the JSON index to disk. */
function saveJsonIndex(entries: GoldEntry[]): void {
  const dir = resolveKmDir();
  ensureDir(dir);
  const path = join(dir, "knowledge-map.json");
  writeFileSync(path, JSON.stringify(entries, null, 2), "utf-8");
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface KmWriteResult {
  /** Number of entries successfully written. */
  written: number;
  /** Number of entries skipped because they were already in the index. */
  duplicatesSkipped: number;
  /** Absolute path to the Markdown log. */
  markdownLogPath: string;
  /** Absolute path to the JSON index. */
  jsonIndexPath: string;
}

/**
 * Write a batch of gold entries to the Knowledge Map.
 * Deduplicates by entry ID before writing.
 */
export function writeToKnowledgeMap(entries: GoldEntry[]): KmWriteResult {
  const dir = resolveKmDir();
  const existing = loadJsonIndex();
  const existingIds = new Set(existing.map((e) => e.id));

  const newEntries = entries.filter((e) => !existingIds.has(e.id));
  const duplicatesSkipped = entries.length - newEntries.length;

  if (newEntries.length > 0) {
    appendToMarkdownLog(newEntries);
    saveJsonIndex([...existing, ...newEntries]);
  }

  return {
    written: newEntries.length,
    duplicatesSkipped,
    markdownLogPath: join(dir, "knowledge-map.md"),
    jsonIndexPath: join(dir, "knowledge-map.json"),
  };
}

/**
 * Search the JSON index for entries matching a query string.
 * Simple case-insensitive substring match across title, body, and tags.
 */
export function searchKnowledgeMap(query: string): GoldEntry[] {
  const lower = query.toLowerCase();
  return loadJsonIndex().filter(
    (e) =>
      e.title.toLowerCase().includes(lower) ||
      e.body.toLowerCase().includes(lower) ||
      e.tags.some((t) => t.toLowerCase().includes(lower)),
  );
}

/** Return all entries in the JSON index. */
export function getAllKnowledgeMapEntries(): GoldEntry[] {
  return loadJsonIndex();
}
